### PR TITLE
bug in quick search fixed, addresses issue #15

### PR DESCRIPTION
**Pull request by shinguz**
quick search works with fix

### CODE REVIEW

**Comment by masakik** [comment]
Hi @shinguz. Thakyou for the contribution. I am not finding time to deploy and test this week but I can merge all 6 pull requests you have made. Just to confirm it.

**Comment by masakik** [comment]
May you add some describing for these updates in readme.md file?

**Comment by shinguz** [comment]
Hi @masakik No problem. take your time. For me it works now :-). By the way: I found some 35 Aigaion installations out there in the internet. I will write to them and point them to your GH branch. Further I have added a note to the original Sourceforge Repo pointing to your GH branch. About the readme.md I hat to look and think... What do you think about increasing the Codeigniter to a recent version 3.? So we would be stable for the next 5 to 10 years... Further I will ask all other GH branches to merge with yours and then delete theires to avoid fragmenting and loosing resources. Cheers, Oli

**Comment by shinguz** [comment]
done.

**Pull request merged**
